apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rewaqxrat-go 
  janus-idp.io/tekton: rewaqxrat-go
  backstage.io/kubernetes-id: rewaqxrat-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rewaqxrat-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  